#!/usr/bin/env python3
"""
Data-Driven 4-Channel Residuals Preprocessor

This script generates 4-channel residuals from trained data-driven models
for fair baseline comparisons. Unlike the old version, this does NOT duplicate
residuals to create 8 channels - it only outputs the 4 data residual channels.

This ensures fair comparison with PINN models that have different physics
and data residuals.
"""

import torch
import numpy as np
import os
import sys
import json
import gc
from typing import Dict, Tuple, Optional, Iterator
import logging

# Try to import tqdm for progress bars (optional)
try:
    from tqdm import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False

# Try to import psutil for memory monitoring (optional)
try:
    import psutil
    HAS_PSUTIL = True
except ImportError:
    HAS_PSUTIL = False
    logger = logging.getLogger(__name__)
    logger.warning("psutil not available - memory monitoring disabled")

# Add project root to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from models.basicPINNv8 import ConfigurableMLP
from training_scripts.common_utils import load_best_model, unified_data_preparation, ensure_double_precision
from training_scripts.pinn_preprocessing import get_optimal_batch_size, load_pinn_data_chunked

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def get_memory_usage() -> float:
    """Get current memory usage in MB."""
    if not HAS_PSUTIL:
        return 0.0
    process = psutil.Process(os.getpid())
    return process.memory_info().rss / 1024 / 1024


def log_memory_usage(message: str = ""):
    """Log current memory usage."""
    if not HAS_PSUTIL:
        return
    memory_mb = get_memory_usage()
    logger.debug(f"{message}: {memory_mb:.1f} MB")


def cleanup_memory():
    """Force garbage collection and clear CUDA cache."""
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def load_pinn_data(pth_file: str, memory_map: bool = False) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Load X and y tensors from .pth files generated by LoadDatav3.py

    Args:
        pth_file: Path to the X .pth file (will automatically load corresponding Y file)
        memory_map: If True, use memory mapping for large files (experimental)

    Returns:
        Tuple of (X, y) tensors
    """
    log_memory_usage("Before loading data")

    # Check if X file exists
    if not os.path.exists(pth_file):
        raise FileNotFoundError(f"X data file not found: {pth_file}")

    try:
        # Load X data
        X = torch.load(pth_file, map_location='cpu')
        log_memory_usage("After loading X data")
    except Exception as e:
        raise ValueError(f"Failed to load X data from {pth_file}: {e}")

    # Construct Y file path
    y_pth_file = pth_file.replace('/X_', '/Y_').replace('\\X_', '\\Y_')
    if pth_file.startswith('X_'):
        y_pth_file = pth_file.replace('X_', 'Y_', 1)
    elif 'X_' in pth_file:
        y_pth_file = pth_file.replace('X_', 'Y_')

    # Check if Y file exists
    if not os.path.exists(y_pth_file):
        raise FileNotFoundError(f"Y data file not found: {y_pth_file}")

    try:
        # Load Y data
        y = torch.load(y_pth_file, map_location='cpu')
        log_memory_usage("After loading Y data")
    except Exception as e:
        raise ValueError(f"Failed to load Y data from {y_pth_file}: {e}")

    # Basic validation
    if X.ndim != 3 or y.ndim != 3:
        raise ValueError(f"Expected 3D tensors, got X: {X.shape}, y: {y.shape}")

    if X.shape[0] != y.shape[0] or X.shape[1] != y.shape[1]:
        raise ValueError(f"Shape mismatch between X {X.shape} and y {y.shape}")

    return X, y


def extract_data_driven_residuals_4ch(model: torch.nn.Module, X: torch.Tensor, y: torch.Tensor,
                                    scaling_params: Dict, device: torch.device, batch_size: Optional[int] = None) -> Dict[str, np.ndarray]:
    """
    Extract 4-channel data-driven residuals from trained model with batch processing.

    Args:
        model: Trained data-driven model
        X: Input features tensor [batch_size, 10]
        y: Target accelerations tensor [batch_size, 4]
        scaling_params: Dictionary with Xmax, Xmin, ymax, ymin
        device: Device to run inference on
        batch_size: Batch size for processing (auto-calculated if None)

    Returns:
        Dictionary with 4 data residual channels only
    """
    model.eval()
    model.to(device)

    # Auto-calculate batch size if not provided
    if batch_size is None:
        batch_size = get_optimal_batch_size(model, X.shape[1])

    total_samples = X.shape[0]
    logger.debug(f"Processing {total_samples} samples in batches of {batch_size}")

    all_data_residuals = []

    # Process in batches
    for start_idx in range(0, total_samples, batch_size):
        end_idx = min(start_idx + batch_size, total_samples)

        # Extract batch
        X_batch = X[start_idx:end_idx].to(device)
        y_batch = y[start_idx:end_idx].to(device)

        # Ensure double precision like in training
        X_batch = X_batch.double()
        y_batch = y_batch.double()

        with torch.no_grad():
            # Normalize inputs
            X_norm = (X_batch - scaling_params['Xmin'].to(device)) / (scaling_params['Xmax'].to(device) - scaling_params['Xmin'].to(device) + 1e-12)

            # Get model predictions
            y_pred_norm = model(X_norm)

            # Denormalize predictions
            y_pred = y_pred_norm * (scaling_params['ymax'].to(device) - scaling_params['ymin'].to(device)) + scaling_params['ymin'].to(device)

            # Calculate residuals (predictions - targets)
            residuals = y_pred - y_batch

            # Convert to numpy and store
            residuals_np = residuals.cpu().numpy()
            all_data_residuals.append(residuals_np)

        # Clean up batch
        del X_batch, y_batch, X_norm, y_pred_norm, y_pred, residuals
        cleanup_memory()

    # Concatenate all residuals
    data_residuals_combined = np.concatenate(all_data_residuals, axis=0)

    # Create 4-channel residual dictionary (NO duplication for fair comparison)
    residuals_dict = {
        # Only data residuals (4 channels) - no physics residual duplication
        'data_res1': data_residuals_combined[:, 0],  # x2_ddot residual
        'data_res2': data_residuals_combined[:, 1],  # y2_ddot residual
        'data_res3': data_residuals_combined[:, 2],  # x3_ddot residual
        'data_res4': data_residuals_combined[:, 3],  # y3_ddot residual
    }

    # Clean up
    del all_data_residuals
    cleanup_memory()

    log_memory_usage("4-channel residual extraction completed")

    # Log shape information
    logger.info(f"Generated 4-channel residuals with {len(data_residuals_combined)} samples")
    for key, residuals in residuals_dict.items():
        logger.info(f"  {key}: shape {residuals.shape}, "
                   f"mean {np.mean(residuals):.6f}, std {np.std(residuals):.6f}")

    return residuals_dict


def extract_data_driven_residuals_4ch_streaming(model: torch.nn.Module, data_iterator: Iterator[Tuple[torch.Tensor, torch.Tensor]],
                                               scaling_params: Dict, device: torch.device, total_chunks: Optional[int] = None) -> Iterator[Dict[str, np.ndarray]]:
    """
    Extract 4-channel data-driven residuals using streaming processing for maximum memory efficiency.

    Args:
        model: Trained data-driven model
        data_iterator: Iterator yielding (X_chunk, y_chunk) tuples
        scaling_params: Dictionary with Xmax, Xmin, ymax, ymin
        device: Device to run inference on
        total_chunks: Total number of chunks for progress tracking

    Yields:
        Dictionary containing residuals for each chunk
    """
    model.eval()
    model.to(device)

    # Use progress bar if tqdm available
    if HAS_TQDM and total_chunks:
        with tqdm(total=total_chunks, desc="Processing chunks", unit="chunk") as pbar:
            for chunk_idx, (X_chunk, y_chunk) in enumerate(data_iterator):
                logger.debug(f"Processing chunk {chunk_idx}")

                # Process this chunk
                residuals_chunk = extract_data_driven_residuals_4ch(model, X_chunk, y_chunk, scaling_params, device)

                log_memory_usage(f"Chunk {chunk_idx} completed")
                pbar.set_postfix({
                    'chunk': f"{chunk_idx + 1}/{total_chunks}",
                    'samples': f"{X_chunk.shape[0]}"
                })

                yield residuals_chunk

                # Clean up
                del residuals_chunk
                cleanup_memory()
                pbar.update(1)
    else:
        # Fallback without progress bar
        for chunk_idx, (X_chunk, y_chunk) in enumerate(data_iterator):
            logger.debug(f"Processing chunk {chunk_idx}")

            # Process this chunk
            residuals_chunk = extract_data_driven_residuals_4ch(model, X_chunk, y_chunk, scaling_params, device)

            log_memory_usage(f"Chunk {chunk_idx} completed")

            yield residuals_chunk

            # Clean up
            del residuals_chunk
            cleanup_memory()


def load_pinn_data_chunked_from_tensor(X_tensor: torch.Tensor, y_tensor: torch.Tensor, chunk_size_mb: int = 100) -> Iterator[Tuple[torch.Tensor, torch.Tensor]]:
    """
    Load X and y tensors in chunks from already loaded tensors.

    Args:
        X_tensor: Input features tensor [total_samples, features]
        y_tensor: Target values tensor [total_samples, features]
        chunk_size_mb: Target chunk size in MB

    Yields:
        Tuples of (X_chunk, y_chunk) tensors
    """
    total_samples = X_tensor.shape[0]
    bytes_per_sample = X_tensor.element_size() * (X_tensor.shape[1] + y_tensor.shape[1])
    target_samples_per_chunk = (chunk_size_mb * 1024 * 1024) // bytes_per_sample

    # Calculate number of chunks for progress bar
    total_chunks = (total_samples + target_samples_per_chunk - 1) // target_samples_per_chunk

    logger.debug(f"Data: {total_samples} samples, ~{bytes_per_sample} bytes per sample")
    logger.debug(f"Target chunk size: {target_samples_per_chunk} samples ({total_chunks} chunks)")

    # Process in chunks
    for start_idx in range(0, total_samples, target_samples_per_chunk):
        end_idx = min(start_idx + target_samples_per_chunk, total_samples)

        # Extract chunk
        X_chunk = X_tensor[start_idx:end_idx]
        y_chunk = y_tensor[start_idx:end_idx]

        log_memory_usage(f"Yielding chunk {start_idx}-{end_idx}")
        yield X_chunk, y_chunk

        # Clean up
        del X_chunk, y_chunk
        cleanup_memory()


def main():
    """Main function to generate 4-channel residuals from data-driven model."""

    import argparse

    parser = argparse.ArgumentParser(description='Generate 4-channel residuals from data-driven model')
    parser.add_argument('--model', type=str, required=True,
                       help='Path to trained data-driven model (.pth file)')
    parser.add_argument('--data-path', type=str, required=True,
                       help='Path to data file (X_*.pth) or directory containing data files')
    parser.add_argument('--output', type=str, required=True,
                       help='Output path for residuals (.pth file)')
    parser.add_argument('--device', type=str, default='cpu',
                       help='Device to use (cpu or cuda)')
    parser.add_argument('--chunk-size-mb', type=int, default=50,
                       help='Target chunk size in MB for streaming processing')
    parser.add_argument('--use-fraction', type=float, default=1.0,
                       help='Fraction of data to use (default: 1.0 for all data, 0.2 for 20%%)')
    parser.add_argument('--test-mode', action='store_true',
                       help='Fast test mode - process only first 10 chunks')

    args = parser.parse_args()

    logger.info("Starting 4-channel residual generation for data-driven baseline")
    logger.info(f"Model: {args.model}")
    logger.info(f"Data: {args.data_path}")
    logger.info(f"Output: {args.output}")
    logger.info(f"Chunk size: {args.chunk_size_mb} MB")
    logger.info(f"Data fraction: {args.use_fraction * 100:.0f}%")
    if args.test_mode:
        logger.info("TEST MODE: Processing only first 10 chunks")

    # Load model
    logger.info("Loading model...")
    model = ConfigurableMLP(
        input_dim=10,  # Standard input dimension
        hidden_layers=[128, 128],  # Best PINN architecture
        output_dim=4,  # 4 acceleration outputs
        activation='elu',
        dropout_rate=0.24900923127192412,
        init_method='xavier_uniform'
    )

    # Load trained weights
    try:
        model.load_state_dict(torch.load(args.model, map_location='cpu'))
        model = model.double()  # Ensure model is in double precision
        logger.info("Model loaded successfully")
    except Exception as e:
        logger.error(f"Failed to load model: {e}")
        return

    # Set up device
    device = torch.device(args.device)
    logger.info(f"Using device: {device}")

    # Determine if data_path is a file or directory
    if os.path.isfile(args.data_path):
        # Single file mode
        data_files = [args.data_path]
        data_dir = os.path.dirname(args.data_path)
    elif os.path.isdir(args.data_path):
        # Directory mode - find all X_*.pth files
        data_dir = args.data_path
        data_files = [os.path.join(data_dir, f) for f in os.listdir(data_dir) if f.startswith('X_') and f.endswith('.pth')]
        if not data_files:
            logger.error(f"No X_*.pth files found in directory {data_dir}")
            return
        logger.info(f"Found {len(data_files)} data files in directory")
    else:
        logger.error(f"Data path {args.data_path} is neither a file nor a directory")
        return

    # Get scaling parameters using the same method as training
    logger.info("Loading data to get scaling parameters (same as training)...")

    # Use the same data loading as training to get scaling parameters
    train_data = unified_data_preparation(
        data_path=data_dir.replace('/v3', '').replace('\\v3', ''),  # Remove /v3 if present
        max_samples=10000,  # Use reasonable sample size
        synthetic=False,
        simulation_id=None,
        batch_size=1000
    )
    train_data = ensure_double_precision(train_data)

    # Extract scaling parameters from the loaded data
    scaling_params = {
        'Xmin': train_data['Xmin'],  # Shape: [1, n_features] or similar
        'Xmax': train_data['Xmax'],
        'ymin': train_data['ymin'],
        'ymax': train_data['ymax']
    }

    logger.info("Loaded scaling parameters from training data")
    logger.info(f"Xmin shape: {scaling_params['Xmin'].shape}")
    logger.info(f"Xmax shape: {scaling_params['Xmax'].shape}")

    # Force CPU usage for lower memory overhead (like PINN preprocessing)
    device = torch.device('cpu')
    logger.info("Using CPU device for maximum memory efficiency")

    # Process each data file
    all_combined_residuals = {}

    for data_file in data_files:
        logger.info(f"Processing data file: {os.path.basename(data_file)}")

        # Calculate total chunks for progress reporting
        # First load data to get dimensions, then clean up immediately
        X_temp, y_temp = load_pinn_data(data_file)
        original_total_samples = X_temp.shape[0] * X_temp.shape[1]

        # Apply fraction to get actual samples we'll process
        if args.use_fraction < 1.0:
            stride = max(1, int(1.0 / args.use_fraction))
            actual_total_samples = (original_total_samples + stride - 1) // stride  # Ceiling division
        else:
            actual_total_samples = original_total_samples

        bytes_per_sample = X_temp.element_size() * (X_temp.shape[2] + y_temp.shape[2])
        target_samples_per_chunk = (args.chunk_size_mb * 1024 * 1024) // bytes_per_sample
        total_chunks = (actual_total_samples + target_samples_per_chunk - 1) // target_samples_per_chunk
        del X_temp, y_temp
        cleanup_memory()

        if args.test_mode:
            total_chunks = min(10, total_chunks)  # Only process first 10 chunks in test mode

        # Use streaming processing for maximum memory efficiency
        logger.info(f"Using streaming processing with {args.chunk_size_mb}MB chunks ({total_chunks} total chunks)")

        # Collect all residuals for this file
        file_residuals = {}
        residual_keys = ['data_res1', 'data_res2', 'data_res3', 'data_res4']

        # Initialize lists for each residual type
        for key in residual_keys:
            file_residuals[key] = []

        # Process in chunks with progress bar
        # Apply fraction sampling by modifying chunk loading
        if args.use_fraction < 1.0:
            # Load full data, apply fraction sampling per rotation speed, then create chunks
            logger.info(f"Applying fraction sampling: {args.use_fraction * 100:.0f}% of data for {os.path.basename(data_file)}")
            X_full, y_full = load_pinn_data(data_file)

            # Calculate stride for sampling within each rotation speed
            stride = max(1, int(1.0 / args.use_fraction))
            logger.info(f"Using sampling stride: {stride} (samples every {stride}th point per rotation speed)")

            # Sample within each rotation speed segment (preserve speed structure)
            n_rot_speeds, n_timestamps_per_speed, n_features_x = X_full.shape
            n_features_y = y_full.shape[2]

            X_sampled = []
            y_sampled = []

            for rot_speed_idx in range(n_rot_speeds):
                # Sample timestamps within this rotation speed
                speed_timestamps = np.arange(0, n_timestamps_per_speed, stride)
                X_speed = X_full[rot_speed_idx, speed_timestamps, :]  # [sampled_timestamps, features]
                y_speed = y_full[rot_speed_idx, speed_timestamps, :]  # [sampled_timestamps, features]

                X_sampled.append(X_speed)
                y_sampled.append(y_speed)

            # Stack back together
            X_full = torch.stack(X_sampled, dim=0)  # [n_rot_speeds, sampled_timestamps, features]
            y_full = torch.stack(y_sampled, dim=0)  # [n_rot_speeds, sampled_timestamps, features]

            original_samples = n_rot_speeds * n_timestamps_per_speed
            new_samples = X_full.shape[0] * X_full.shape[1]
            logger.info(f"Data reduced from {original_samples} to {new_samples} samples "
                       f"({original_samples//n_rot_speeds} -> {new_samples//n_rot_speeds} per rotation speed)")

            # Flatten the sampled data and use chunked loading
            X_full = X_full.reshape(-1, n_features_x)  # [total_samples, features]
            y_full = y_full.reshape(-1, n_features_y)  # [total_samples, features]

            # Create data iterator using chunked loading
            data_iterator = load_pinn_data_chunked_from_tensor(X_full, y_full, args.chunk_size_mb)
            residuals_iterator = extract_data_driven_residuals_4ch_streaming(model, data_iterator, scaling_params, device, total_chunks)
        else:
            # Use standard chunked loading for full data
            data_iterator = load_pinn_data_chunked(data_file, args.chunk_size_mb)
            residuals_iterator = extract_data_driven_residuals_4ch_streaming(model, data_iterator, scaling_params, device, total_chunks)

        chunk_count = 0
        if HAS_TQDM:
            with tqdm(total=total_chunks, desc=f"Processing {os.path.basename(data_file)}", unit="chunk") as overall_pbar:
                for chunk_residuals in residuals_iterator:
                    chunk_count += 1
                    logger.debug(f"Processed chunk {chunk_count}/{total_chunks}")
                    # Accumulate residuals from this chunk
                    for key in residual_keys:
                        file_residuals[key].append(chunk_residuals[key])
                    overall_pbar.update(1)

                    if args.test_mode and chunk_count >= 10:
                        logger.info("TEST MODE: Stopping after 10 chunks")
                        break
        else:
            # Fallback without progress bar
            for chunk_residuals in residuals_iterator:
                chunk_count += 1
                logger.debug(f"Processed chunk {chunk_count}/{total_chunks}")
                # Accumulate residuals from this chunk
                for key in residual_keys:
                    file_residuals[key].append(chunk_residuals[key])

                if args.test_mode and chunk_count >= 10:
                    logger.info("TEST MODE: Stopping after 10 chunks")
                    break

        logger.info(f"Processed {chunk_count} chunks for {os.path.basename(data_file)}")

        # Concatenate chunks for this file
        file_combined_residuals = {}
        for key in residual_keys:
            file_combined_residuals[key] = np.concatenate(file_residuals[key], axis=0)

        # Accumulate across files
        for key in residual_keys:
            if key not in all_combined_residuals:
                all_combined_residuals[key] = []
            all_combined_residuals[key].append(file_combined_residuals[key])

    # Concatenate all files
    log_memory_usage("Concatenating results from all files")
    final_residuals = {}
    for key in residual_keys:
        final_residuals[key] = np.concatenate(all_combined_residuals[key], axis=0)

    # Clean up
    del all_combined_residuals
    cleanup_memory()

    # Save residuals with higher pickle protocol to handle large files
    logger.info(f"Saving 4-channel residuals to {args.output}")

    # Convert numpy arrays to torch tensors for efficient saving
    torch_dict = {}
    for key, residuals in final_residuals.items():
        torch_dict[key] = torch.from_numpy(residuals).float()

    # Use pickle protocol 4 to handle large files (>4GB)
    import pickle
    with open(args.output, 'wb') as f:
        pickle.dump(torch_dict, f, protocol=4)

    logger.info(f"Successfully saved {len(torch_dict)} residual channels")

    # Log final statistics
    logger.info("Final residual statistics:")
    for key, residuals in final_residuals.items():
        logger.info(f"  {key}: {len(residuals)} samples, "
                   f"mean {np.mean(residuals):.6f}, std {np.std(residuals):.6f}")

    if args.test_mode:
        logger.info("✅ TEST MODE: 4-channel residual generation completed (partial)!")
    else:
        logger.info("✅ 4-channel residual generation completed!")


if __name__ == '__main__':
    main()
