#!/usr/bin/env python3
"""
PINN Residuals Preprocessor (Memory Optimized)

This module provides functions to extract PINN residuals from trained models
for use as features in other experiments. It loads data from .pth files
generated by LoadDatav3.py and returns residuals in memory.

Memory optimizations:
- Batch processing to avoid loading entire datasets
- Memory cleanup with explicit garbage collection
- Optional memory mapping for large files
- Streaming processing for large datasets
"""

import torch
import numpy as np
import os
import sys
import json
import gc
from typing import Dict, Tuple, Optional, Iterator
import logging

# Try to import tqdm for progress bars (optional)
try:
    from tqdm import tqdm
    HAS_TQDM = True
except ImportError:
    HAS_TQDM = False

# Try to import psutil for memory monitoring (optional)
try:
    import psutil
    HAS_PSUTIL = True
except ImportError:
    HAS_PSUTIL = False
    logger = logging.getLogger(__name__)
    logger.warning("psutil not available - memory monitoring disabled")

# Add project root to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from training_scripts.common_utils import load_best_model

# Setup logging (reduced verbosity to avoid spam)
logging.basicConfig(level=logging.WARNING)
logger = logging.getLogger(__name__)


# ============================================================================
# UNIFORM MODEL LOADING REGISTRY
# ============================================================================

def load_retrained_pinn_model(model_name: str, device: torch.device):
    """
    Load a retrained PINN model from train_best_models.py results.

    Args:
        model_name: Name of the PINN method
        device: Device to load the model on

    Returns:
        Tuple of (model, scaling_params)
    """
    model, scaling_params, config = load_best_model(model_name, device=device)
    return model, scaling_params


def load_data_driven_model(model_name: str, device: torch.device):
    """
    Load a data-driven model.

    Args:
        model_name: Either 'data_standard' or 'data_reg'
        device: Device to load the model on

    Returns:
        Tuple of (model, scaling_params)
    """
    # Map model names to paths
    if model_name == 'data_standard':
        data_driven_model_path = "results/data_driven_standard"
    elif model_name == 'data_reg':
        data_driven_model_path = "results/data_driven_reg"
    else:
        raise ValueError(f"Unknown data-driven model: {model_name}. Use 'data_standard' or 'data_reg'")

    # Ensure path is absolute
    if not os.path.isabs(data_driven_model_path):
        project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        data_driven_model_path = os.path.join(project_root, data_driven_model_path)

    model_path = os.path.join(data_driven_model_path, "best_model.pth")
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Data-driven model file not found: {model_path}")

    # Import here to avoid circular imports
    from models.basicPINNv8 import ConfigurableMLP

    # Create model with fixed architecture
    model = ConfigurableMLP(
        input_dim=10,
        hidden_layers=[128, 128],
        output_dim=4,
        activation='elu',
        dropout_rate=0.24900923127192412,
        init_method='xavier_uniform'
    )

    # Load weights
    state_dict = torch.load(model_path, map_location=device)
    model.load_state_dict(state_dict)
    model = model.double().to(device)

    # Load scaling parameters
    scaling_path = os.path.join(data_driven_model_path, "scaling_params.npz")
    if not os.path.exists(scaling_path):
        raise FileNotFoundError(f"Scaling parameters not found for data-driven model: {scaling_path}")

    scaling_data = np.load(scaling_path)
    scaling_params = {
        'Xmin': torch.from_numpy(scaling_data['Xmin']).double(),
        'Xmax': torch.from_numpy(scaling_data['Xmax']).double(),
        'ymin': torch.from_numpy(scaling_data['ymin']).double(),
        'ymax': torch.from_numpy(scaling_data['ymax']).double()
    }

    return model, scaling_params


# Model registry mapping model names to loading functions
MODEL_REGISTRY = {
    # All PINN models (retrained using train_best_models.py)
    'relobralo': load_retrained_pinn_model,
    'constant_weight': load_retrained_pinn_model,
    'brdr': load_retrained_pinn_model,
    'pecann': load_retrained_pinn_model,
    'adaptive_lbpin': load_retrained_pinn_model,
    'alpinn': load_retrained_pinn_model,
    'dwpinn': load_retrained_pinn_model,
    'gradnorm': load_retrained_pinn_model,

    # Data-driven models
    'data_standard': load_data_driven_model,
    'data_reg': load_data_driven_model,
}

# List of all available models
AVAILABLE_MODELS = list(MODEL_REGISTRY.keys())


def get_memory_usage() -> float:
    """Get current memory usage in MB."""
    if not HAS_PSUTIL:
        return 0.0
    process = psutil.Process(os.getpid())
    return process.memory_info().rss / 1024 / 1024


def log_memory_usage(message: str = ""):
    """Log current memory usage."""
    if not HAS_PSUTIL:
        return
    memory_mb = get_memory_usage()
    logger.debug(".1f")  # Changed from info to debug to reduce spam


def cleanup_memory():
    """Force garbage collection and clear CUDA cache."""
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def load_pinn_data(pth_file: str, memory_map: bool = False) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Load X and y tensors from .pth files generated by LoadDatav3.py

    Args:
        pth_file: Path to the X .pth file (will automatically load corresponding Y file)
        memory_map: If True, use memory mapping for large files (experimental)

    Returns:
        Tuple of (X, y) tensors where:
        - X: Input features [n_rotation_speeds, n_timestamps_per_speed, 10]
        - y: Target accelerations [n_rotation_speeds, n_timestamps_per_speed, 4]

    Raises:
        FileNotFoundError: If X or Y file doesn't exist
        ValueError: If data format is unexpected
    """
    log_memory_usage("Before loading data")

    # Check if X file exists
    if not os.path.exists(pth_file):
        raise FileNotFoundError(f"X data file not found: {pth_file}")

    try:
        # Load X data with optional memory mapping
        if memory_map:
            # Use mmap for large files (experimental)
            X = torch.load(pth_file, map_location='cpu', mmap=True)
        else:
            X = torch.load(pth_file, map_location='cpu')
        log_memory_usage("After loading X data")
    except Exception as e:
        raise ValueError(f"Failed to load X data from {pth_file}: {e}")

    # Construct Y file path by replacing X with Y
    y_pth_file = pth_file.replace('/X_', '/Y_').replace('\\X_', '\\Y_')
    if pth_file.startswith('X_'):
        y_pth_file = pth_file.replace('X_', 'Y_', 1)
    elif 'X_' in pth_file:
        y_pth_file = pth_file.replace('X_', 'Y_')

    # Check if Y file exists
    if not os.path.exists(y_pth_file):
        raise FileNotFoundError(f"Y data file not found: {y_pth_file}")

    try:
        # Load Y data
        if memory_map:
            y = torch.load(y_pth_file, map_location='cpu', mmap=True)
        else:
            y = torch.load(y_pth_file, map_location='cpu')
        log_memory_usage("After loading Y data")
    except Exception as e:
        raise ValueError(f"Failed to load Y data from {y_pth_file}: {e}")

    # Basic validation of data shapes
    if X.ndim != 3 or y.ndim != 3:
        raise ValueError(f"Expected 3D tensors, got X: {X.shape}, y: {y.shape}")

    if X.shape[0] != y.shape[0] or X.shape[1] != y.shape[1]:
        raise ValueError(f"Shape mismatch between X {X.shape} and y {y.shape}")

    return X, y


def load_pinn_data_chunked(pth_file: str, chunk_size_mb: int = 100) -> Iterator[Tuple[torch.Tensor, torch.Tensor]]:
    """
    Load X and y tensors in chunks to save memory.

    Args:
        pth_file: Path to the X .pth file
        chunk_size_mb: Target chunk size in MB

    Yields:
        Tuples of (X_chunk, y_chunk) tensors
    """
    # First load the full data to understand structure
    X_full, y_full = load_pinn_data(pth_file)

    # Calculate chunk size based on memory target
    total_samples = X_full.shape[0] * X_full.shape[1]
    bytes_per_sample = X_full.element_size() * (X_full.shape[2] + y_full.shape[2])
    target_samples_per_chunk = (chunk_size_mb * 1024 * 1024) // bytes_per_sample

    # Calculate number of chunks for progress bar
    total_chunks = (total_samples + target_samples_per_chunk - 1) // target_samples_per_chunk

    logger.debug(f"Data: {total_samples} samples, ~{bytes_per_sample} bytes per sample")
    logger.debug(f"Target chunk size: {target_samples_per_chunk} samples ({total_chunks} chunks)")

    # Process in chunks with progress bar if tqdm available
    if HAS_TQDM:
        with tqdm(total=total_chunks, desc="Loading data chunks", unit="chunk") as pbar:
            for start_idx in range(0, total_samples, target_samples_per_chunk):
                end_idx = min(start_idx + target_samples_per_chunk, total_samples)

                # Extract chunk from flattened data
                X_chunk = X_full.reshape(-1, X_full.shape[2])[start_idx:end_idx]
                y_chunk = y_full.reshape(-1, y_full.shape[2])[start_idx:end_idx]

                log_memory_usage(f"Yielding chunk {start_idx}-{end_idx}")
                pbar.set_postfix({
                    'samples': f"{start_idx}-{end_idx}",
                    'size': f"{X_chunk.shape[0]} samples"
                })

                yield X_chunk, y_chunk

                # Clean up
                del X_chunk, y_chunk
                cleanup_memory()
                pbar.update(1)
    else:
        # Fallback without progress bar
        for start_idx in range(0, total_samples, target_samples_per_chunk):
            end_idx = min(start_idx + target_samples_per_chunk, total_samples)

            # Extract chunk from flattened data
            X_chunk = X_full.reshape(-1, X_full.shape[2])[start_idx:end_idx]
            y_chunk = y_full.reshape(-1, y_full.shape[2])[start_idx:end_idx]

            log_memory_usage(f"Yielding chunk {start_idx}-{end_idx}")

            yield X_chunk, y_chunk

            # Clean up
            del X_chunk, y_chunk
            cleanup_memory()

    # Clean up full data
    del X_full, y_full
    cleanup_memory()


def get_optimal_batch_size(model: torch.nn.Module, sample_size: int, max_memory_mb: int = 500) -> int:
    """
    Calculate optimal batch size based on available memory.

    Args:
        model: The PINN model
        sample_size: Size of input features (e.g., 10)
        max_memory_mb: Maximum memory to use for batch processing

    Returns:
        Optimal batch size
    """
    # Estimate memory per sample (rough approximation)
    # Model parameters + activations + gradients
    param_count = sum(p.numel() for p in model.parameters())
    estimated_bytes_per_sample = (param_count * 4) + (sample_size * 4) + 1000  # Rough estimate

    # Reserve some memory for overhead
    available_bytes = max_memory_mb * 1024 * 1024 * 0.7

    batch_size = int(available_bytes // estimated_bytes_per_sample)
    batch_size = max(1, min(batch_size, 10000))  # Reasonable bounds

    logger.debug(f"Estimated batch size: {batch_size} (max memory: {max_memory_mb}MB)")
    return batch_size


def extract_pinn_residuals(model: torch.nn.Module, X: torch.Tensor, y: torch.Tensor,
                          scaling_params: Dict, device: torch.device, batch_size: Optional[int] = None) -> Dict[str, np.ndarray]:
    """
    Extract PINN residuals from the model predictions with batch processing.

    Args:
        model: Trained PINN model
        X: Input features tensor [batch_size, 10]
        y: Target accelerations tensor [batch_size, 4]
        scaling_params: Scaling parameters for normalization/denormalization
        device: Device to run on
        batch_size: Batch size for processing (auto-calculated if None)

    Returns:
        Dictionary containing residuals
    """
    model.eval()
    log_memory_usage("Starting residual extraction")

    # Auto-calculate batch size if not provided
    if batch_size is None:
        batch_size = get_optimal_batch_size(model, X.shape[1])

    total_samples = X.shape[0]
    logger.debug(f"Processing {total_samples} samples in batches of {batch_size}")

    # Check if this is a data-driven model (ConfigurableMLP)
    from models.basicPINNv8 import ConfigurableMLP
    is_data_driven = isinstance(model, ConfigurableMLP)

    # Initialize lists to collect residuals
    all_data_residuals = []
    if is_data_driven:
        # Data-driven models don't have physics residuals, only data residuals
        all_phys_res1 = all_phys_res2 = all_phys_res3 = all_phys_res4 = []
    else:
        # PINN models have both data and physics residuals
        all_phys_res1, all_phys_res2, all_phys_res3, all_phys_res4 = [], [], [], []

    # Process in batches
    for start_idx in range(0, total_samples, batch_size):
        end_idx = min(start_idx + batch_size, total_samples)

        # Extract batch
        X_batch = X[start_idx:end_idx].to(device)
        y_batch = y[start_idx:end_idx].to(device)

        log_memory_usage(f"Processing batch {start_idx}-{end_idx}")  # This will now be debug level

        # Normalize inputs
        X_norm = (X_batch - scaling_params['Xmin']) / (scaling_params['Xmax'] - scaling_params['Xmin'] + 1e-12)

        with torch.no_grad():
            # Get model predictions
            y_pred_norm = model(X_norm)

            # Denormalize predictions
            y_pred = y_pred_norm * (scaling_params['ymax'] - scaling_params['ymin']) + scaling_params['ymin']

            if is_data_driven:
                # For data-driven models, only compute data residuals
                # Physics residuals will be set to data residuals for compatibility
                pass  # No physics residuals computation needed
            else:
                # Get physics residuals from PINN model
                residuals_result = model.compute_residuals(X_norm, y_pred_norm,
                                                         scaling_params['Xmax'].to(device),
                                                         scaling_params['Xmin'].to(device),
                                                         scaling_params['ymax'].to(device),
                                                         scaling_params['ymin'].to(device))

                # Handle different return formats
                if isinstance(residuals_result, dict):
                    residuals = residuals_result['residuals']
                else:
                    residuals = residuals_result

                # Unpack residuals (excluding mass residuals)
                res1, res2, res3, res4, _, _ = residuals

        # Data residuals (prediction errors) - already in physical space
        data_residuals = (y_pred - y_batch).cpu().numpy()

        # Collect data residuals
        all_data_residuals.append(data_residuals)

        if is_data_driven:
            # For data-driven models, physics residuals are the same as data residuals for compatibility
            all_phys_res1.append(data_residuals[:, 0])
            all_phys_res2.append(data_residuals[:, 1])
            all_phys_res3.append(data_residuals[:, 2])
            all_phys_res4.append(data_residuals[:, 3])
        else:
            # Physics residuals are already in physical space (computed with denormalized values)
            # Just convert to numpy
            phys_res1_vals = res1.cpu().numpy()
            phys_res2_vals = res2.cpu().numpy()
            phys_res3_vals = res3.cpu().numpy()
            phys_res4_vals = res4.cpu().numpy()

            # Collect physics residuals
            all_phys_res1.append(phys_res1_vals)
            all_phys_res2.append(phys_res2_vals)
            all_phys_res3.append(phys_res3_vals)
            all_phys_res4.append(phys_res4_vals)

        # Clean up batch
        del X_batch, y_batch, X_norm, y_pred_norm, y_pred
        if not is_data_driven:
            del residuals_result
        if 'residuals' in locals():
            del residuals
        cleanup_memory()

    # Concatenate all batches
    log_memory_usage("Concatenating results")  # This will now be debug level
    data_residuals_combined = np.concatenate(all_data_residuals, axis=0)

    residuals_dict = {
        # Data residuals (4 components)
        'data_res1': data_residuals_combined[:, 0],  # x2_ddot residual
        'data_res2': data_residuals_combined[:, 1],  # y2_ddot residual
        'data_res3': data_residuals_combined[:, 2],  # x3_ddot residual
        'data_res4': data_residuals_combined[:, 3],  # y3_ddot residual

        # Physics residuals (4 components, excluding mass)
        'phys_res1': np.concatenate(all_phys_res1, axis=0),
        'phys_res2': np.concatenate(all_phys_res2, axis=0),
        'phys_res3': np.concatenate(all_phys_res3, axis=0),
        'phys_res4': np.concatenate(all_phys_res4, axis=0),
    }

    # Clean up
    del all_data_residuals, all_phys_res1, all_phys_res2, all_phys_res3, all_phys_res4
    cleanup_memory()

    log_memory_usage("Residual extraction completed")  # This will now be debug level
    return residuals_dict


def extract_pinn_residuals_streaming(model: torch.nn.Module, data_iterator: Iterator[Tuple[torch.Tensor, torch.Tensor]],
                                    scaling_params: Dict, device: torch.device, total_chunks: Optional[int] = None) -> Iterator[Dict[str, np.ndarray]]:
    """
    Extract PINN residuals using streaming processing for maximum memory efficiency.

    Args:
        model: Trained PINN model
        data_iterator: Iterator yielding (X_chunk, y_chunk) tuples
        scaling_params: Scaling parameters for normalization/denormalization
        device: Device to run on
        total_chunks: Total number of chunks for progress bar (optional)

    Yields:
        Dictionary containing residuals for each chunk
    """
    model.eval()
    log_memory_usage("Starting streaming residual extraction")  # This will now be debug level

    # Use progress bar if tqdm available
    if HAS_TQDM and total_chunks:
        with tqdm(total=total_chunks, desc="Processing chunks", unit="chunk") as pbar:
            for chunk_idx, (X_chunk, y_chunk) in enumerate(data_iterator):
                logger.debug(f"Processing chunk {chunk_idx}")

                # Process this chunk
                residuals_chunk = extract_pinn_residuals(model, X_chunk, y_chunk, scaling_params, device)

                log_memory_usage(f"Chunk {chunk_idx} completed")  # This will now be debug level
                pbar.set_postfix({
                    'chunk': f"{chunk_idx + 1}/{total_chunks}",
                    'samples': f"{X_chunk.shape[0]}"
                })

                yield residuals_chunk

                # Clean up
                del residuals_chunk
                cleanup_memory()
                pbar.update(1)
    else:
        # Fallback without progress bar
        for chunk_idx, (X_chunk, y_chunk) in enumerate(data_iterator):
            logger.debug(f"Processing chunk {chunk_idx}")

            # Process this chunk
            residuals_chunk = extract_pinn_residuals(model, X_chunk, y_chunk, scaling_params, device)

            log_memory_usage(f"Chunk {chunk_idx} completed")  # This will now be debug level

            yield residuals_chunk

            # Clean up
            del residuals_chunk
            cleanup_memory()


def validate_model_predictions(model, scaling_params, device, sample_data=None):
    """Validate that model predictions are in reasonable ranges."""
    print("[VALIDATION] Validating model predictions...")

    if sample_data is None:
        # Create some sample data for validation
        sample_X = torch.randn(10, 10, device=device, dtype=torch.float64)  # 10 samples, 10 features
        sample_y = torch.randn(10, 4, device=device, dtype=torch.float64)   # 10 samples, 4 outputs
    else:
        sample_X, sample_y = sample_data

    # Normalize sample input
    X_norm = (sample_X - scaling_params['Xmin']) / (scaling_params['Xmax'] - scaling_params['Xmin'] + 1e-12)

    model.eval()
    with torch.no_grad():
        y_pred_norm = model(X_norm)
        y_pred = y_pred_norm * (scaling_params['ymax'] - scaling_params['ymin']) + scaling_params['ymin']

    # Check prediction ranges
    y_pred_mean = torch.mean(y_pred).item()
    y_pred_std = torch.std(y_pred).item()
    y_pred_min = torch.min(y_pred).item()
    y_pred_max = torch.max(y_pred).item()

    print(f"   Model predictions - Mean: {y_pred_mean:.2e}, Std: {y_pred_std:.2e}")
    print(f"   Model predictions - Min: {y_pred_min:.2e}, Max: {y_pred_max:.2e}")

    # Check if predictions are reasonable (not all zeros, not infinite, not extremely large)
    if torch.allclose(y_pred, torch.zeros_like(y_pred), atol=1e-6):
        print("   [WARNING] Model predictions are all zeros!")
    elif torch.any(torch.isinf(y_pred)) or torch.any(torch.isnan(y_pred)):
        print("   [ERROR] Model predictions contain inf or nan values!")
    elif torch.max(torch.abs(y_pred)) > 1e10:
        print("   [WARNING] Extremely large prediction values detected!")
    else:
        print("   [SUCCESS] Model predictions appear reasonable")

    return y_pred






def preprocess_pinn_data(model_name: str, data_path: str, chunk_size_mb: int = 50) -> Dict[str, np.ndarray]:
    """
    Preprocess data using a trained PINN or data-driven model to extract residuals (maximum memory efficiency).

    Uses streaming processing to handle large datasets with minimal RAM usage.
    All PINN models are retrained versions from train_best_models.py using optimal hyperparameters.

    Args:
        model_name: Name of the trained model. Must be one of:
            PINN models (all retrained): 'relobralo', 'constant_weight', 'brdr', 'pecann',
                                        'adaptive_lbpin', 'alpinn', 'dwpinn', 'gradnorm'
            Data-driven models: 'data_standard', 'data_reg'
        data_path: Path to .pth data file (from LoadDatav3.py)
        chunk_size_mb: Target chunk size in MB (smaller = less RAM, slower processing)

    Returns:
        Dictionary containing 8 residual features:
        - data_res1, data_res2, data_res3, data_res4: Data residuals
        - phys_res1, phys_res2, phys_res3, phys_res4: Physics residuals (or repeated data residuals for data-driven)
    """
    log_memory_usage("Starting maximum memory efficiency preprocessing")  # This will now be debug level

    # Force CPU usage for lower memory overhead
    device = torch.device('cpu')
    logger.debug(f"Using CPU device for maximum memory efficiency")

    # Validate model name
    if model_name not in MODEL_REGISTRY:
        available = ', '.join(AVAILABLE_MODELS)
        raise ValueError(f"Unknown model '{model_name}'. Available models: {available}")

    # Load model and scaling parameters using uniform registry
    logger.info(f"Loading model '{model_name}'")
    load_function = MODEL_REGISTRY[model_name]
    model, scaling_params = load_function(model_name, device)

    # Determine if this is a data-driven model for extraction logic
    is_data_driven = model_name in ['data_standard', 'data_reg']

    # Define extraction function based on model type
    if is_data_driven:
        def extract_residuals_func(model, X_chunk, y_chunk, scaling_params, device):
            """Extract residuals from data-driven model (simpler than PINN)."""
            model.eval()
            total_samples = X_chunk.shape[0]
            batch_size = get_optimal_batch_size(model, X_chunk.shape[1])

            all_data_residuals = []

            for start_idx in range(0, total_samples, batch_size):
                end_idx = min(start_idx + batch_size, total_samples)
                X_batch = X_chunk[start_idx:end_idx].to(device).double()
                y_batch = y_chunk[start_idx:end_idx].to(device).double()

                X_norm = (X_batch - scaling_params['Xmin']) / (scaling_params['Xmax'] - scaling_params['Xmin'] + 1e-12)

                with torch.no_grad():
                    y_pred_norm = model(X_norm)
                    y_pred = y_pred_norm * (scaling_params['ymax'] - scaling_params['ymin']) + scaling_params['ymin']

                data_residuals = (y_pred - y_batch).cpu().numpy()
                all_data_residuals.append(data_residuals)

                del X_batch, y_batch, X_norm, y_pred_norm, y_pred
                cleanup_memory()

            data_residuals_combined = np.concatenate(all_data_residuals, axis=0)

            # For compatibility, repeat data residuals as physics residuals
            return {
                'data_res1': data_residuals_combined[:, 0],
                'data_res2': data_residuals_combined[:, 1],
                'data_res3': data_residuals_combined[:, 2],
                'data_res4': data_residuals_combined[:, 3],
                'phys_res1': data_residuals_combined[:, 0],  # Repeated for compatibility
                'phys_res2': data_residuals_combined[:, 1],
                'phys_res3': data_residuals_combined[:, 2],
                'phys_res4': data_residuals_combined[:, 3],
            }
        residuals_extraction_fn = extract_residuals_func
    else:
        # Use PINN extraction (includes physics residuals)
        residuals_extraction_fn = None  # Will use extract_pinn_residuals

    log_memory_usage("Model loaded")  # This will now be debug level

    # Validate model predictions with a small sample (only for PINN models)
    if not is_data_driven:
        validate_model_predictions(model, scaling_params, device)

    # Calculate total chunks for progress reporting
    # First load data to get dimensions, then clean up immediately
    X_temp, y_temp = load_pinn_data(data_path)
    total_samples = X_temp.shape[0] * X_temp.shape[1]
    bytes_per_sample = X_temp.element_size() * (X_temp.shape[2] + y_temp.shape[2])
    target_samples_per_chunk = (chunk_size_mb * 1024 * 1024) // bytes_per_sample
    total_chunks = (total_samples + target_samples_per_chunk - 1) // target_samples_per_chunk
    del X_temp, y_temp
    cleanup_memory()

    # Use streaming processing for maximum memory efficiency
    logger.debug(f"Using streaming processing with {chunk_size_mb}MB chunks ({total_chunks} total chunks)")

    # Collect all residuals
    all_residuals = {}
    residual_keys = ['data_res1', 'data_res2', 'data_res3', 'data_res4',
                    'phys_res1', 'phys_res2', 'phys_res3', 'phys_res4']

    # Initialize lists for each residual type
    for key in residual_keys:
        all_residuals[key] = []

    # Process in chunks with progress bar
    data_iterator = load_pinn_data_chunked(data_path, chunk_size_mb)

    # Use appropriate extraction function
    if is_data_driven:
        # Use data-driven extraction
        def streaming_extraction():
            for chunk_idx, (X_chunk, y_chunk) in enumerate(data_iterator):
                yield residuals_extraction_fn(model, X_chunk, y_chunk, scaling_params, device)
        residuals_iterator = streaming_extraction()
    else:
        # Use PINN extraction (includes physics residuals)
        residuals_iterator = extract_pinn_residuals_streaming(model, data_iterator, scaling_params, device, total_chunks)

    if HAS_TQDM:
        with tqdm(total=total_chunks, desc="Preprocessing data", unit="chunk") as overall_pbar:
            for chunk_residuals in residuals_iterator:
                # Accumulate residuals from this chunk
                for key in residual_keys:
                    all_residuals[key].append(chunk_residuals[key])
                overall_pbar.update(1)
    else:
        # Fallback without progress bar
        for chunk_residuals in residuals_iterator:
            # Accumulate residuals from this chunk
            for key in residual_keys:
                all_residuals[key].append(chunk_residuals[key])

    # Concatenate all chunks
    log_memory_usage("Concatenating streaming results")  # This will now be debug level
    final_residuals = {}
    for key in residual_keys:
        final_residuals[key] = np.concatenate(all_residuals[key], axis=0)

    # Clean up
    del all_residuals
    cleanup_memory()

    log_memory_usage("Maximum memory efficiency preprocessing completed")  # This will now be debug level
    return final_residuals


def get_residual_features(residuals_dict: Dict[str, np.ndarray]) -> np.ndarray:
    """
    Convert residuals dictionary to feature matrix for machine learning.

    Args:
        residuals_dict: Dictionary from preprocess_pinn_data

    Returns:
        Feature matrix of shape [num_samples, 8]
    """
    features = np.column_stack([
        residuals_dict['data_res1'], residuals_dict['data_res2'],
        residuals_dict['data_res3'], residuals_dict['data_res4'],
        residuals_dict['phys_res1'], residuals_dict['phys_res2'],
        residuals_dict['phys_res3'], residuals_dict['phys_res4']
    ])
    return features


def get_rotation_speed_separated_features(data_path: str, model_name: str = 'relobralo',
                                       chunk_size_mb: int = 50) -> np.ndarray:
    """
    Get features separated by rotation speed: [n_rotation_speeds, n_timestamps_per_speed, 8] (maximum memory efficiency)

    Args:
        data_path: Path to .pth file from LoadDatav3.py
        model_name: Name of trained PINN model
        chunk_size_mb: Target chunk size in MB for streaming processing
        use_bayesian_models: If True, use models from Bayesian optimization instead of retrained models

    Returns:
        Array of shape [n_rotation_speeds, n_timestamps_per_speed, 8]
    """
    log_memory_usage("Starting rotation speed separated features (maximum memory efficiency)")  # This will now be debug level

    # Load raw data to get dimensions
    X, y = load_pinn_data(data_path)
    n_rotation_speeds, n_timestamps_per_speed = X.shape[0], X.shape[1]
    log_memory_usage(f"Data shape: {X.shape}")  # This will now be debug level

    # Clean up the initial data load immediately
    del X, y
    cleanup_memory()

    # Get residuals using maximum memory efficiency preprocessing
    residuals = preprocess_pinn_data(model_name, data_path, chunk_size_mb)

    # Convert to feature matrix
    features_flat = get_residual_features(residuals)  # [total_samples, 8]

    # Reshape back to separated format
    features_separated = features_flat.reshape(
        n_rotation_speeds,
        n_timestamps_per_speed,
        8
    )

    # Clean up
    del residuals, features_flat
    cleanup_memory()

    log_memory_usage("Rotation speed separated features completed")  # This will now be debug level
    return features_separated


# ============================================================================
# UNIFORM PINN PREPROCESSING
# ============================================================================
#
# This module provides uniform access to all retrained PINN and data-driven models
# for residual extraction from large datasets with minimal RAM usage.
#
# AVAILABLE MODELS:
#   PINN Models (8 total, all retrained using train_best_models.py):
#     - 'relobralo', 'constant_weight', 'brdr', 'pecann'
#     - 'adaptive_lbpin', 'alpinn', 'dwpinn', 'gradnorm'
#
#   Data-Driven Models (2 total):
#     - 'data_standard', 'data_reg'
#
# BASIC USAGE:
#   from training_scripts.pinn_preprocessing import preprocess_pinn_data
#   residuals = preprocess_pinn_data('relobralo', 'Data/v3/X_normal_v3.pth')
#
# CONTROL MEMORY USAGE:
#   # Smaller chunks = less RAM, slower processing
#   residuals = preprocess_pinn_data('relobralo', 'Data/v3/X_normal_v3.pth', chunk_size_mb=25)
#
#   # Larger chunks = more RAM, faster processing
#   residuals = preprocess_pinn_data('relobralo', 'Data/v3/X_normal_v3.pth', chunk_size_mb=100)
#
# ROTATION SPEED FEATURES:
#   from training_scripts.pinn_preprocessing import get_rotation_speed_separated_features
#   features = get_rotation_speed_separated_features('Data/v3/X_normal_v3.pth', 'relobralo')
#
# MODEL LOADING:
#   - All models use their saved scaling parameters for consistent normalization
#   - All PINN models are retrained versions from train_best_models.py results
#   - Data-driven models load from their respective result directories
#   - No fallback to data-derived scaling - all models must have proper scaling parameters
#
# EXAMPLE USAGE:
#   # Any of the 8 PINN models (all retrained)
#   relobralo_residuals = preprocess_pinn_data('relobralo', 'Data/v3/X_normal_v3.pth')
#   adaptive_residuals = preprocess_pinn_data('adaptive_lbpin', 'Data/v3/X_normal_v3.pth')
#   gradnorm_residuals = preprocess_pinn_data('gradnorm', 'Data/v3/X_normal_v3.pth')
#
#   # Data-driven models
#   data_std_residuals = preprocess_pinn_data('data_standard', 'Data/v3/X_normal_v3.pth')
#   data_reg_residuals = preprocess_pinn_data('data_reg', 'Data/v3/X_normal_v3.pth')
#
# TRAINING MODELS:
#   # Retrain all 8 PINN models with their best hyperparameters
#   python train_best_models.py --data-path Data/v3 --max-samples 50000
#
# FEATURES:
#   - Streaming processing (loads data in chunks)
#   - Automatic memory cleanup
#   - CPU-only processing for lower memory overhead
#   - Memory monitoring (if psutil installed)
#   - Progress bars (if tqdm installed)
#   - Uniform model loading registry
#
# OPTIONAL DEPENDENCIES:
#   pip install psutil  # Memory usage monitoring
#   pip install tqdm    # Progress bars during processing
#
# ============================================================================