#!/usr/bin/env python3
"""
Overnight OSR Siamese Analysis Runner

This script runs the Siamese analysis pipeline for multiple models:
- Uses all .pth files from best_model_residuals/ folder (generated by pinn_to_siamese_wrapper.py)
- Different combinations of known fault classes (normal + 2-4 additional faults)
- Optimized training parameters for each model type
- Special handling for data-driven models (4-channel configuration)
- Saves all results in overnight_osr_experiments/ folder
- Test mode available with --test flag (only 3 combinations)

Full run: N models × 15 combinations
Test run: N models × 3 combinations (1 trial each for k=3,4,5)
"""

import itertools
import subprocess
import sys
import time
import os
import argparse
from datetime import datetime
import logging

# Set up logging
def setup_logging():
    """Set up logging to track the overnight runs"""
    log_filename = f"overnight_run_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(log_filename),
            logging.StreamHandler(sys.stdout)
        ]
    )
    return logging.getLogger(__name__)

def parse_args():
    """Parse command line arguments"""
    parser = argparse.ArgumentParser(description="Overnight OSR Siamese Analysis Runner")
    parser.add_argument('--test', action='store_true',
                        help='Run in test mode with only 3 combinations instead of 15')
    parser.add_argument('--output-dir', type=str, default='overnight_osr_experiments',
                        help='Main output directory for all results (default: overnight_osr_experiments)')
    return parser.parse_args()

# Configuration for Multiple Models
RESIDUALS_DIR = "best_model_residuals"

# Dynamically find all .pth files in the residuals directory
if os.path.exists(RESIDUALS_DIR):
    RESIDUAL_FILES = [f for f in os.listdir(RESIDUALS_DIR) if f.endswith('.pth')]
    RESIDUAL_FILES = [os.path.join(RESIDUALS_DIR, f) for f in RESIDUAL_FILES]
else:
    RESIDUAL_FILES = []
    print(f"Warning: {RESIDUALS_DIR} directory not found!")

# All fault classes (excluding normal which is always included)
FAULT_CLASSES = [
    "overhang_ball_fault",
    "overhang_cage_fault", 
    "overhang_outer_race_fault",
    "underhang_ball_fault",
    "underhang_cage_fault",
    "underhang_outer_race_fault",
    "horizontal_misalignment_fault",
    "vertical_misalignment_fault",
    "imbalance_fault"
]

# Fixed arguments for all runs (optimized for data-driven models)
FIXED_ARGS = [
    "--num-triplets", "10000",
    "--epochs", "5",  # Increased for better training
    "--batch-size", "128",
    "--n-folds", "2",  # Increased for better validation
    "--num-trials", "1",  # More trials for better hyperparameter search
    "--num-top-models", "1",  # Keep more top models
    "--num-repeat-runs", "1",  # More repeat runs for stability
    "--verbose", "1",
    "--device", "cpu",
    "--source", "direct"
]

def generate_random_known_class_combinations(num_trials_per_k=10, k_values=[4, 5], random_seed=42):
    """
    Generate random combinations of known classes:
    - Always include 'normal'
    - For each k (total known classes), generate num_trials_per_k random combinations
    
    Args:
        num_trials_per_k: Number of random trials per k value
        k_values: List of k values (total number of known classes) to test
        random_seed: Random seed for reproducibility
    
    Returns:
        List of tuples, each containing a combination of known classes
    """
    import random
    random.seed(random_seed)
    
    combinations = []
    
    for k in k_values:
        num_additional = k - 1  # Subtract 1 because 'normal' is always included
        
        if num_additional > len(FAULT_CLASSES):
            print(f"Warning: Cannot generate {k} known classes: only {len(FAULT_CLASSES)} fault classes available")
            continue
            
        # Generate num_trials_per_k random combinations for this k
        generated_combinations = set()  # Use set to avoid duplicates
        attempts = 0
        max_attempts = num_trials_per_k * 10  # Prevent infinite loops
        
        while len(generated_combinations) < num_trials_per_k and attempts < max_attempts:
            # Randomly select num_additional fault classes (excluding 'normal')
            available_faults = [f for f in FAULT_CLASSES if f != 'normal']
            fault_combo = tuple(sorted(random.sample(available_faults, num_additional)))
            known_classes = tuple(['normal'] + list(fault_combo))
            
            generated_combinations.add(known_classes)
            attempts += 1
        
        combinations.extend(list(generated_combinations))
        print(f"Generated {len(generated_combinations)} random combinations for k={k}")
    
    return combinations

def create_output_dir_name(residual_file, known_classes):
    """
    Create a descriptive output directory path within the main output folder

    Args:
        residual_file: Path to the residual file (e.g., "best_model_residuals/relobralo_residuals.pth")
        known_classes: Tuple of known class names

    Returns:
        String representing the output directory path
    """
    # Extract model name from residual file path
    model_name = os.path.basename(residual_file).replace("_residuals.pth", "")

    # Create a short representation of known classes
    fault_classes = [cls for cls in known_classes if cls != "normal"]
    fault_abbrev = "_".join([cls.replace("_fault", "").replace("_", "")[:8] for cls in fault_classes])

    # Create timestamp for uniqueness
    timestamp = datetime.now().strftime("%m%d_%H%M")

    return os.path.join(MAIN_OUTPUT_DIR, f"{model_name}_{len(known_classes)}classes_{fault_abbrev}_{timestamp}")

def run_siamese_analysis(residual_file, known_classes, output_dir, logger):
    """
    Run a single instance of the Siamese analysis

    Args:
        residual_file: Path to the residual file
        known_classes: List of known class names
        output_dir: Output directory name
        logger: Logger instance

    Returns:
        Tuple of (success: bool, runtime: float)
    """
    start_time = time.time()

    # Build the command
    cmd = [
        sys.executable, "-m", "siamese_analysis_v3.cli",
        "--residuals", residual_file,
        "--output-dir", output_dir,
        "--known-classes"] + list(known_classes) + FIXED_ARGS

    # Add special flags for data-driven models (ensure only 4 channels)
    model_name = os.path.basename(residual_file).replace("_residuals.pth", "")
    if "data_driven" in model_name.lower():
        cmd.extend(["--num-channels", "4"])
        logger.info(f"Using 4-channel configuration for data-driven model: {model_name}")

    logger.info(f"Starting run: {output_dir}")
    logger.info(f"Residual file: {residual_file}")
    logger.info(f"Model: {model_name}")
    logger.info(f"Known classes: {known_classes}")
    if "data_driven" in model_name.lower():
        logger.info(f"Applied 4-channel configuration for data-driven model")
    logger.info(f"Command: {' '.join(cmd)}")
    
    try:
        # Run the command and capture output
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=3600  # 1 hour timeout per run
        )
        
        runtime = time.time() - start_time
        
        if result.returncode == 0:
            # Check if expected output files were created
            expected_files = [
                os.path.join(output_dir, "search_results", "best_model.pt"),
                os.path.join(output_dir, "search_results", "top_models.json"),
                os.path.join(output_dir, "classification_report_level2.txt")
            ]
            missing_outputs = [f for f in expected_files if not os.path.exists(f)]
            if missing_outputs:
                logger.warning(f"CLI returned success but some expected files are missing: {missing_outputs}")
                logger.warning(f"This might indicate incomplete analysis for: {output_dir}")
                return False, runtime
            else:
                logger.info(f"SUCCESS: {output_dir} (runtime: {runtime:.1f}s)")
                return True, runtime
        else:
            logger.error(f"FAILED: {output_dir} (runtime: {runtime:.1f}s)")
            logger.error(f"STDOUT: {result.stdout[-500:]}")  # Last 500 chars
            logger.error(f"STDERR: {result.stderr[-500:]}")  # Last 500 chars
            return False, runtime
            
    except subprocess.TimeoutExpired:
        runtime = time.time() - start_time
        logger.error(f"TIMEOUT: {output_dir} (runtime: {runtime:.1f}s)")
        return False, runtime
        
    except Exception as e:
        runtime = time.time() - start_time
        logger.error(f"EXCEPTION: {output_dir} (runtime: {runtime:.1f}s) - {str(e)}")
        return False, runtime

def estimate_total_time(num_combinations, avg_time_per_run=180):
    """
    Estimate total runtime

    Args:
        num_combinations: Total number of combinations to run
        avg_time_per_run: Average time per run in seconds (default 180s = 3 min)

    Returns:
        Estimated total time in hours
    """
    total_seconds = num_combinations * avg_time_per_run
    return total_seconds / 3600

def main():
    """Main function to run the overnight analysis"""
    # Parse command line arguments
    args = parse_args()

    # Set the main output directory from command line argument
    global MAIN_OUTPUT_DIR
    MAIN_OUTPUT_DIR = args.output_dir

    logger = setup_logging()

    if args.test:
        logger.info("Starting Overnight OSR Siamese Analysis Runner (TEST MODE)")
        logger.info("=" * 60)
    else:
        logger.info("Starting Overnight OSR Siamese Analysis Runner")
        logger.info("=" * 60)

    # Create main output directory if it doesn't exist
    os.makedirs(MAIN_OUTPUT_DIR, exist_ok=True)
    logger.info(f"Created main output directory: {MAIN_OUTPUT_DIR}")

    # Generate random combinations - fewer in test mode
    if args.test:
        logger.info("TEST MODE: Using only 3 combinations (1 trial each for k=3,4,5)")
        known_class_combinations = generate_random_known_class_combinations(
            num_trials_per_k=1,  # Only 1 trial per k value in test mode
            k_values=[3, 4, 5],
            random_seed=42
        )
    else:
        # Generate random combinations for k=3, 4, and 5 (5 trials each)
        known_class_combinations = generate_random_known_class_combinations(
            num_trials_per_k=5,
            k_values=[3, 4, 5],
            random_seed=42
        )
    total_combinations = len(RESIDUAL_FILES) * len(known_class_combinations)

    logger.info(f"Analysis Summary:")
    logger.info(f"   Models (residual files): {len(RESIDUAL_FILES)}")
    if args.test:
        logger.info(f"   K-values to test: [3, 4, 5] (1 random trial each - TEST MODE)")
    else:
        logger.info(f"   K-values to test: [3, 4, 5] (5 random trials each)")
    logger.info(f"   Known class combinations: {len(known_class_combinations)}")
    logger.info(f"   Total runs: {total_combinations} ({len(RESIDUAL_FILES)} models × {len(known_class_combinations)} combinations)")
    logger.info(f"   Estimated time: {estimate_total_time(total_combinations):.1f} hours")  # 3 minutes per run
    logger.info("=" * 60)
    
    # Check if residual files exist
    missing_files = []
    for residual_file in RESIDUAL_FILES:
        if not os.path.exists(residual_file):
            missing_files.append(residual_file)
    
    if missing_files:
        logger.error(f"Missing residual files: {missing_files}")
        logger.error("Please ensure all residual files are in the best_model_residuals directory")
        return 1
    
    # Run all combinations with intercalated residual files
    # This ensures we progress evenly across all residuals
    start_time = time.time()
    successful_runs = 0
    failed_runs = 0
    
    run_count = 0
    
    # Intercalate: for each known_class combination, run all residual files before moving to next combination
    for known_classes in known_class_combinations:
        for residual_file in RESIDUAL_FILES:
            run_count += 1
            
            # Create output directory name
            output_dir = create_output_dir_name(residual_file, known_classes)
            
            logger.info(f"\nRun {run_count}/{total_combinations}")
            
            # Run the analysis
            success, runtime = run_siamese_analysis(residual_file, known_classes, output_dir, logger)
            
            if success:
                successful_runs += 1
            else:
                failed_runs += 1
            
            # Log progress every 10 runs
            if run_count % 10 == 0:
                elapsed_time = (time.time() - start_time) / 3600
                avg_time_per_run = elapsed_time * 3600 / run_count
                remaining_time = (total_combinations - run_count) * avg_time_per_run / 3600
                
                logger.info(f"Progress: {run_count}/{total_combinations} ({run_count/total_combinations*100:.1f}%)")
                logger.info(f"   Successful: {successful_runs}, Failed: {failed_runs}")
                logger.info(f"   Elapsed: {elapsed_time:.1f}h, Estimated remaining: {remaining_time:.1f}h")
        
        # Log completion of each known_class combination across all residuals
        combo_num = known_class_combinations.index(known_classes) + 1
        logger.info(f"Completed combination {combo_num}/{len(known_class_combinations)}: {known_classes}")
        logger.info(f"   Progress across all combinations: {combo_num/len(known_class_combinations)*100:.1f}%")
    
    # Final summary
    total_time = (time.time() - start_time) / 3600
    logger.info("\n" + "=" * 60)
    if args.test:
        logger.info("TEST MODE: Overnight OSR Siamese Analysis Complete!")
    else:
        logger.info("Overnight OSR Siamese Analysis Complete!")
    logger.info(f"Final Summary:")
    logger.info(f"   Total runs: {total_combinations} ({len(RESIDUAL_FILES)} models × {len(known_class_combinations)} combinations)")
    logger.info(f"   Successful: {successful_runs}")
    logger.info(f"   Failed: {failed_runs}")
    logger.info(f"   Success rate: {successful_runs/total_combinations*100:.1f}%")
    logger.info(f"   Total time: {total_time:.1f} hours")
    logger.info(f"   Average time per run: {total_time*3600/total_combinations:.1f} seconds")
    logger.info(f"   Results saved in: {MAIN_OUTPUT_DIR}/")
    logger.info("=" * 60)
    
    return 0 if failed_runs == 0 else 1

if __name__ == "__main__":
    sys.exit(main())
